<?php

namespace ContainerH8cLa9c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MkC9pHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mkC9pH_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mkC9pH_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ligneFraisForfait' => ['privates', '.errored..service_locator.mkC9pH_.App\\Entity\\LigneFraisForfait', NULL, 'Cannot autowire service ".service_locator.mkC9pH_": it references class "App\\Entity\\LigneFraisForfait" but no such service exists.'],
            'ligneFraisForfaitRepository' => ['privates', 'App\\Repository\\LigneFraisForfaitRepository', 'getLigneFraisForfaitRepositoryService', true],
        ], [
            'ligneFraisForfait' => 'App\\Entity\\LigneFraisForfait',
            'ligneFraisForfaitRepository' => 'App\\Repository\\LigneFraisForfaitRepository',
        ]);
    }
}
