<?php

namespace ContainerH8cLa9c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T8MmAbdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t8MmAbd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t8MmAbd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ligneFraisHorsForfaitRepository' => ['privates', 'App\\Repository\\LigneFraisHorsForfaitRepository', 'getLigneFraisHorsForfaitRepositoryService', true],
        ], [
            'ligneFraisHorsForfaitRepository' => 'App\\Repository\\LigneFraisHorsForfaitRepository',
        ]);
    }
}
