<?php

namespace ContainerH8cLa9c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JIs8aDAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jIs8aDA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jIs8aDA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etatRepository' => ['privates', 'App\\Repository\\EtatRepository', 'getEtatRepositoryService', true],
        ], [
            'etatRepository' => 'App\\Repository\\EtatRepository',
        ]);
    }
}
