<?php

namespace ContainerH8cLa9c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3jCfkvDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3jCfkvD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3jCfkvD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etat' => ['privates', '.errored..service_locator.3jCfkvD.App\\Entity\\Etat', NULL, 'Cannot autowire service ".service_locator.3jCfkvD": it references class "App\\Entity\\Etat" but no such service exists.'],
        ], [
            'etat' => 'App\\Entity\\Etat',
        ]);
    }
}
