<?php

namespace ContainerH8cLa9c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneFraisForfait2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mkC9pH_.App\Entity\LigneFraisForfait' shared service.
     *
     * @return \App\Entity\LigneFraisForfait
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mkC9pH_": it references class "App\\Entity\\LigneFraisForfait" but no such service exists.');
    }
}
