<?php

namespace ContainerXTALwGU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3jCfkvD.App\Entity\Etat' shared service.
     *
     * @return \App\Entity\Etat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3jCfkvD": it references class "App\\Entity\\Etat" but no such service exists.');
    }
}
