<?php

namespace ContainerXTALwGU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneFraisHorsForfaitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4P_.3_9.App\Entity\LigneFraisHorsForfait' shared service.
     *
     * @return \App\Entity\LigneFraisHorsForfait
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4P_.3_9": it references class "App\\Entity\\LigneFraisHorsForfait" but no such service exists.');
    }
}
