<?php

namespace ContainerXTALwGU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneFraisForfaitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.go.YzM8.App\Entity\LigneFraisForfait' shared service.
     *
     * @return \App\Entity\LigneFraisForfait
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.go.YzM8": it references class "App\\Entity\\LigneFraisForfait" but no such service exists.');
    }
}
