<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FicheFrais extends \App\Entity\FicheFrais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'user', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'nb_justificatif', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisHorsForfaits', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisForfaits'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'user', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'nb_justificatif', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisHorsForfaits', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisForfaits'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FicheFrais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?\App\Entity\Etat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(?\App\Entity\Etat $etat): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbJustificatif(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbJustificatif', []);

        return parent::getNbJustificatif();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbJustificatif(int $nb_justificatif): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbJustificatif', [$nb_justificatif]);

        return parent::setNbJustificatif($nb_justificatif);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant(float $montant): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneFraisHorsForfaits(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneFraisHorsForfaits', []);

        return parent::getLigneFraisHorsForfaits();
    }

    /**
     * {@inheritDoc}
     */
    public function addLigneFraisHorsForfait(\App\Entity\LigneFraisHorsForfait $ligneFraisHorsForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLigneFraisHorsForfait', [$ligneFraisHorsForfait]);

        return parent::addLigneFraisHorsForfait($ligneFraisHorsForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneFraisHorsForfait(\App\Entity\LigneFraisHorsForfait $ligneFraisHorsForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneFraisHorsForfait', [$ligneFraisHorsForfait]);

        return parent::removeLigneFraisHorsForfait($ligneFraisHorsForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneFraisForfaits(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneFraisForfaits', []);

        return parent::getLigneFraisForfaits();
    }

    /**
     * {@inheritDoc}
     */
    public function addLigneFraisForfait(\App\Entity\LigneFraisForfait $ligneFraisForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLigneFraisForfait', [$ligneFraisForfait]);

        return parent::addLigneFraisForfait($ligneFraisForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneFraisForfait(\App\Entity\LigneFraisForfait $ligneFraisForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneFraisForfait', [$ligneFraisForfait]);

        return parent::removeLigneFraisForfait($ligneFraisForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
