<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnNd5Zx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnNd5Zx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEnNd5Zx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEnNd5Zx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEnNd5Zx\App_KernelDevDebugContainer([
    'container.build_hash' => 'EnNd5Zx',
    'container.build_id' => 'f6c2fec4',
    'container.build_time' => 1651054365,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnNd5Zx');
